#!/usr/bin/env bash
# Build deploy/Caddyfile from .env (PUBLIC_HOST / PUBLIC_DOMAIN, TLS mode).

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

if [[ ! -f .env ]]; then
  echo "Missing .env"
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

if [[ "${HTTPS_ENABLED:-0}" != "1" ]]; then
  echo "HTTPS_ENABLED is not 1 — Caddyfile not generated."
  exit 0
fi

SITE="${PUBLIC_DOMAIN:-${PUBLIC_HOST:-localhost}}"
OUT="${ROOT_DIR}/deploy/Caddyfile"

is_ip() {
  [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
}

{
  echo "# Auto-generated by deploy/generate-caddyfile.sh — do not edit manually."
  if is_ip "${SITE}"; then
    # Let's Encrypt and Caddy internal TLS do not work reliably for bare IPs in browsers.
    echo "{"
    echo "    auto_https off"
    echo "}"
    echo ":80 {"
    echo "    reverse_proxy gateway-service:8000"
    echo "}"
  else
    echo "${SITE} {"
    if [[ "${TLS_MODE:-auto}" == "internal" ]]; then
      echo "    tls internal"
    fi
    echo "    reverse_proxy gateway-service:8000"
    echo "}"
  fi
} > "${OUT}"

echo "Caddyfile written (${OUT})"
if is_ip "${SITE}"; then
  echo "Bare IP: HTTP on port 80 — open http://${SITE}/"
  echo "For trusted HTTPS set PUBLIC_DOMAIN to your domain in .env."
else
  echo "Site: https://${SITE}/"
fi
