server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://gateway-service:8000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /assets/ {
    expires 7d;
    try_files $uri @spa;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location @spa {
    try_files /index.html =404;
  }
}
