import { Environment, Grid, Html, OrbitControls, TransformControls, useTexture } from '@react-three/drei';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Suspense, useEffect, useMemo, useRef, useState } from 'react';
import { SRGBColorSpace, type Group, type Mesh } from 'three';
import { usePlanner, type Furniture } from './store';

const textureUrls:Record<string,string>={wood_dark_oak:'/api/frontend-assets/textures/wood/dark-oak/basecolor.png',wood_oak:'/api/frontend-assets/textures/wood/light-oak/basecolor.png',board_black:'/api/frontend-assets/textures/board/black-board/basecolor.png',board_white:'/api/frontend-assets/textures/board/white-board/basecolor-v2.png',fabric_gray:'/api/frontend-assets/textures/fabric/gray-weave/basecolor.png',metal_graphite:'/api/frontend-assets/textures/metal/graphite-brush/basecolor.png',mdf_matte:'/api/frontend-assets/textures/mdf/matte-soft/basecolor-v2.png',laminate_grey:'/api/frontend-assets/textures/laminate/gray-laminate/basecolor-v2.png',countertop:'/api/frontend-assets/textures/stone/countertop-sand/basecolor-v2.png'};
Object.values(textureUrls).forEach(url=>useTexture.preload(url));

function DynamicWalls(){const room=usePlanner(s=>s.room);const front=useRef<Mesh>(null);const back=useRef<Mesh>(null);const left=useRef<Mesh>(null);const right=useRef<Mesh>(null);const side=useRef({x:1,z:1});useFrame(({camera})=>{const x=camera.position.x,z=camera.position.z;if(x>.2)side.current.x=1;else if(x<-.2)side.current.x=-1;if(z>.2)side.current.z=1;else if(z<-.2)side.current.z=-1;if(front.current)front.current.visible=side.current.z<0;if(back.current)back.current.visible=side.current.z>0;if(left.current)left.current.visible=side.current.x>0;if(right.current)right.current.visible=side.current.x<0});const w=room.width/1000,l=room.length/1000,h=room.height/1000;return <group><Wall ref={back} position={[0,h/2,-l/2]} size={[w,.05,h]}/><Wall ref={front} position={[0,h/2,l/2]} size={[w,.05,h]}/><Wall ref={left} position={[-w/2,h/2,0]} size={[.05,l,h]}/><Wall ref={right} position={[w/2,h/2,0]} size={[.05,l,h]}/></group>}
function Wall({position,size,ref}:{position:[number,number,number];size:[number,number,number];ref:React.Ref<Mesh>}){return <mesh ref={ref} position={position} receiveShadow><boxGeometry args={size}/><meshStandardMaterial color="#f3efe8" roughness={.9}/></mesh>}
function Panel({position,scale,textureKey,color,neutral=false}:{position:[number,number,number];scale:[number,number,number];textureKey:string;color:string;neutral?:boolean}){const source=useTexture(textureUrls[neutral?'board_white':textureKey]??textureUrls.wood_oak);const map=useMemo(()=>{const clone=source.clone();clone.colorSpace=SRGBColorSpace;clone.needsUpdate=true;return clone},[source]);useEffect(()=>()=>map.dispose(),[map]);return <mesh position={position} castShadow receiveShadow><boxGeometry args={scale}/><meshStandardMaterial map={color?undefined:map} color={color||'#ffffff'} roughness={textureKey==='metal_graphite' ? .3 : .62} metalness={textureKey==='metal_graphite' ? .85 : 0}/></mesh>}
function FurnitureParts({item}:{item:Furniture}){const w=item.width/1000,d=item.depth/1000,h=item.height/1000,t=.018,gap=.008;const p={textureKey:item.texture,color:item.color};if(item.type==='table')return <><Panel position={[0,h-t/2,0]} scale={[w,t,d]} {...p}/>{[-1,1].flatMap(x=>[-1,1].map(z=><Panel key={`${x}:${z}`} position={[x*w*.4,h/2,z*d*.38]} scale={[.05,h,.05]} textureKey="metal_graphite" color=""/>))}</>;if(item.type==='sofa')return <><Panel position={[0,h*.28,0]} scale={[w,h*.35,d]} {...p}/><Panel position={[0,h*.65,-d*.38]} scale={[w,h*.65,d*.18]} {...p}/><Panel position={[-w*.46,h*.45,0]} scale={[w*.08,h*.45,d]} {...p}/><Panel position={[w*.46,h*.45,0]} scale={[w*.08,h*.45,d]} {...p}/></>;if(item.type==='shelf')return <><Panel position={[-w/2+t/2,h/2,0]} scale={[t,h,d]} {...p}/><Panel position={[w/2-t/2,h/2,0]} scale={[t,h,d]} {...p}/>{Array.from({length:5},(_,i)=><Panel key={i} position={[0,h*i/4,t/2]} scale={[w,t,d]} {...p}/>)}</>;const count=item.type==='wardrobe'?Math.max(2,item.handles):Math.max(1,item.drawers||2);return <><Panel position={[-w/2+t/2,h/2,0]} scale={[t,h,d]} textureKey={item.texture} color="" neutral/><Panel position={[w/2-t/2,h/2,0]} scale={[t,h,d]} textureKey={item.texture} color="" neutral/><Panel position={[0,t/2,0]} scale={[w,t,d]} textureKey={item.texture} color="" neutral/><Panel position={[0,h-t/2,0]} scale={[w,t,d]} textureKey={item.texture} color="" neutral/><Panel position={[0,h/2,-d/2+t/2]} scale={[w-t*2,h-t*2,t]} textureKey="board_white" color=""/>{Array.from({length:count},(_,i)=>{const fh=(h-t*2)/count;return <group key={i}><Panel position={[0,t+fh*(i+.5),d/2+t*.55]} scale={[w-gap,fh-gap,t]} {...p}/><Panel position={[item.type==='wardrobe'?(i%2?-.04:.04):w*.32,t+fh*(i+.5),d/2+t*1.6]} scale={[.012,.1,.025]} textureKey="metal_graphite" color=""/></group>})}<Panel position={[0,.045,-d*.08]} scale={[w*.82,.09,d*.72]} textureKey="board_black" color=""/></>}
function FurnitureMesh({item}:{item:Furniture}){const select=usePlanner(s=>s.select);const selected=usePlanner(s=>s.selected===item.id);const update=usePlanner(s=>s.update);const room=usePlanner(s=>s.room);const[node,setNode]=useState<Group|null>(null);const w=item.width/1000,d=item.depth/1000,h=item.height/1000;const x=item.x/1000-room.width/2000,z=item.z/1000-room.length/2000;const sync=()=>{if(!node)return;update(item.id,{x:Math.round((node.position.x+room.width/2000)*1000),z:Math.round((node.position.z+room.length/2000)*1000)})};const content=<group ref={setNode} position={[x,0,z]} rotation-y={item.rotation*Math.PI/180} onClick={e=>{e.stopPropagation();select(item.id)}}><FurnitureParts item={item}/>{selected&&<><mesh position={[0,h/2,0]}><boxGeometry args={[w+.04,h+.04,d+.04]}/><meshBasicMaterial color="#d2764a" wireframe/></mesh><Html position={[0,h+.18,0]} center distanceFactor={8}><span className="whitespace-nowrap rounded-full bg-[#211c18] px-3 py-1 text-xs font-bold text-white">{item.width} × {item.height} × {item.depth} мм</span></Html></>}</group>;return <>{content}{selected&&node&&<TransformControls object={node} mode="translate" showY={false} onObjectChange={sync}/>}</>}
function CameraMode({top}:{top:boolean}){const{camera}=useThree();useEffect(()=>{camera.position.set(top ? 0 : 7,top ? 9 : 5.5,top ? .01 : 7.5);camera.lookAt(0,top ? 0 : 1,0)},[camera,top]);return null}
function Scene({top}:{top:boolean}){const items=usePlanner(s=>s.items);const room=usePlanner(s=>s.room);const select=usePlanner(s=>s.select);return <><CameraMode top={top}/><color attach="background" args={['#e7e1d9']}/><ambientLight intensity={.35}/><hemisphereLight intensity={.55} color="#fff7ed" groundColor="#d7dee8"/><directionalLight castShadow intensity={1.8} position={[4.2,9,4.6]} shadow-mapSize={[2048,2048]} shadow-normalBias={.015}/><directionalLight intensity={.45} color="#e6edf7" position={[-5.4,3.2,-2.6]}/><Suspense fallback={null}><Environment preset="apartment"/><DynamicWalls/><mesh rotation-x={-Math.PI/2} receiveShadow onClick={()=>select(null)}><planeGeometry args={[room.width/1000,room.length/1000]}/><meshStandardMaterial color="#c8a67d" roughness={.8}/></mesh><Grid position={[0,.006,0]} args={[room.width/1000,room.length/1000]} cellSize={.25} cellColor="#8b7964" sectionColor="#5d5145" fadeDistance={12}/>{items.map(item=><FurnitureMesh key={item.id} item={item}/>)}</Suspense><OrbitControls makeDefault target={[0,1,0]} minDistance={2} maxDistance={18} maxPolarAngle={top ? .05 : Math.PI/2.02}/></>}
export function PlannerCanvas({top=false}:{top?:boolean}){return <Canvas shadows dpr={[1,1.7]} camera={{position:top?[0,9,.01]:[7,5.5,7.5],fov:45}} gl={{antialias:true}}><Scene top={top}/></Canvas>}
