import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from './features/auth/AuthProvider';
import { ThemeProvider } from './features/theme/ThemeProvider';
import { App } from './App';
import './styles/globals.css';
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:30_000,retry:1}}});
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><QueryClientProvider client={queryClient}><ThemeProvider><AuthProvider><App/></AuthProvider></ThemeProvider></QueryClientProvider></BrowserRouter></React.StrictMode>);
