import { api, schemas, type ApiFurniture, type Project } from './api';
import type { Furniture, FurnitureType, Room } from '../features/planner/store';

export type EditorSnapshot={version:1;room:Room;items:Furniture[]};
export type ProjectPayload={name:string;location:string;user_id:string;room_width:number;room_length:number;room_height:number;price_standard:number;price_comfort:number;price_premium:number;bom_json:string;selected_tier:'standard'};
const allowedTypes=new Set(['wardrobe','cabinet','shelf','table','sofa']);
const editorId=()=>crypto.randomUUID();

export function apiFurnitureToEditor(row:ApiFurniture):Furniture{return{id:editorId(),backendId:row.id,type:(allowedTypes.has(row.furniture_type)?row.furniture_type:'cabinet') as FurnitureType,name:row.name,width:row.width,depth:row.depth,height:row.height,x:row.x,z:row.z,rotation:row.rotation_y,texture:row.texture||'wood_oak',color:row.custom_color||'',drawers:row.drawers,handles:row.handles}}
export function projectSnapshot(project:Project):EditorSnapshot|null{if(!project.bom_json)return null;try{const value=JSON.parse(project.bom_json) as Partial<EditorSnapshot>;if(value.version===1&&value.room&&Array.isArray(value.items))return value as EditorSnapshot}catch{return null}return null}
export function estimate(items:Furniture[]){const rates:Record<string,number>={wood_dark_oak:1.25,wood_oak:1,board_black:.9,board_white:.82,fabric_gray:1.1,metal_graphite:1.2,mdf_matte:1.05,laminate_grey:.88,countertop:1.35};const standard=Math.round(items.reduce((sum,item)=>{const area=(item.width*item.height*2+item.depth*item.height*2+item.width*item.depth*2)/1_000_000;return sum+area*6200*(rates[item.texture]??1)+item.drawers*2400+item.handles*450},0));return{standard,comfort:Math.round(standard*1.22),premium:Math.round(standard*1.52)}}
export function editorToProjectPayload(input:{name:string;location:string;user:string;room:Room;items:Furniture[]}):ProjectPayload{const prices=estimate(input.items);const snapshot:EditorSnapshot={version:1,room:input.room,items:input.items.map(item=>({...item,backendId:undefined}))};return{name:input.name,location:input.location,user_id:input.user,room_width:input.room.width,room_length:input.room.length,room_height:input.room.height,price_standard:prices.standard,price_comfort:prices.comfort,price_premium:prices.premium,bom_json:JSON.stringify(snapshot),selected_tier:'standard'}}
export async function loadEditorProject(projectId:number,user:string,signal?:AbortSignal){const projects=await api.get(`/planner/projects/user/${encodeURIComponent(user)}`,schemas.project.array(),signal);const project=projects.find(row=>row.id===projectId);if(!project)throw new Error('Проект не найден или принадлежит другому пользователю.');const snapshot=projectSnapshot(project);const rows=snapshot?.items??(await api.get(`/planner/projects/${projectId}/furniture`,schemas.furniture.array(),signal)).map(apiFurnitureToEditor);return{project,room:snapshot?.room??{width:project.room_width,length:project.room_length,height:project.room_height},items:rows}}
export async function saveEditorProject(input:{projectId:number|null;name:string;location:string;user:string;room:Room;items:Furniture[]}){const payload=editorToProjectPayload(input);const project=input.projectId?await api.patch(`/planner/projects/${input.projectId}`,payload,schemas.project):await api.post('/planner/projects',payload,schemas.project);if(!input.projectId){for(const item of input.items)await api.post(`/planner/projects/${project.id}/furniture`,{name:item.name,width:item.width,depth:item.depth,height:item.height,x:item.x,y:0,z:item.z,rotation_y:item.rotation,furniture_type:item.type,texture:item.texture,custom_color:item.color,drawers:item.drawers,handles:item.handles},schemas.furniture)}return project}
