import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { PackagePlus,Search,ShieldAlert,Trash2,X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../components/ui/button';
import { useAuth } from '../features/auth/AuthProvider';
import { money,rankProducts } from '../lib/utils';
import { api,schemas,type Product } from '../services/api';
type Draft={name:string;sku:string;brand:string;description:string;price:number;stock:number;category_id:number|null};
const empty=():Draft=>({name:'',sku:'',brand:'',description:'',price:1000,stock:0,category_id:null});
export function AdminPage(){
 const{roles}=useAuth();const client=useQueryClient();const[query,setQuery]=useState('');const[editing,setEditing]=useState<Product|null>(null);const[editorOpen,setEditorOpen]=useState(false);const[draft,setDraft]=useState<Draft>(empty());
 const allowed=roles.some(x=>['admin','catalog:write'].includes(x.toLowerCase()));
 const products=useQuery({queryKey:['admin','products'],queryFn:({signal})=>api.get('/catalog/products?limit=100&sort_by=name&is_active=true',schemas.product.array(),signal),enabled:allowed});
 const categories=useQuery({queryKey:['catalog','categories'],queryFn:({signal})=>api.get('/catalog/categories',schemas.category.array(),signal),enabled:allowed});
 const refresh=()=>Promise.all([client.invalidateQueries({queryKey:['admin','products']}),client.invalidateQueries({queryKey:['catalog','products']})]);
 const close=()=>{setEditorOpen(false);setEditing(null);setDraft(empty())};
 const save=useMutation({mutationFn:()=>editing?api.patch(`/catalog/products/${editing.id}`,{name:draft.name,brand:draft.brand,description:draft.description,price:draft.price,stock:draft.stock,category_id:draft.category_id},schemas.product):api.post('/catalog/products',{...draft,is_active:true},schemas.product),onSuccess:()=>{close();refresh()}});
 const remove=useMutation({mutationFn:(id:number)=>api.delete(`/catalog/products/${id}`),onSuccess:refresh});
 const open=(product?:Product)=>{setEditing(product??null);setDraft(product?{name:product.name,sku:product.sku,brand:product.brand,description:product.description,price:product.price,stock:product.stock,category_id:product.category_id}:empty());setEditorOpen(true)};
 if(!allowed)return <div className="container py-24"><ShieldAlert className="size-10 text-destructive"/><h1 className="mt-5 font-display text-4xl font-bold">Недостаточно прав</h1><p className="mt-3 text-muted-foreground">Раздел доступен ролям admin и catalog:write.</p></div>;
 const rows=rankProducts(products.data??[],query);const error=products.error||save.error||remove.error;
 return <div className="container py-14"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-widest text-primary">Управление</p><h1 className="mt-2 font-display text-5xl font-bold">Каталог</h1></div><Button onClick={()=>open()}><PackagePlus/>Новый товар</Button></div><label className="mt-8 flex max-w-xl items-center gap-3 rounded-2xl border bg-card px-4 py-3"><Search className="size-5 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск в административном каталоге" className="w-full bg-transparent outline-none"/></label>{error&&<p className="mt-5 rounded-xl bg-destructive/10 p-4 text-destructive">{error.message}</p>}<div className="mt-8 overflow-x-auto rounded-2xl border bg-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b bg-muted"><tr><th className="p-4">Товар</th><th>SKU</th><th>Цена</th><th>Остаток</th><th/></tr></thead><tbody>{products.isLoading?<tr><td className="p-6" colSpan={5}>Загружаем реальные данные...</td></tr>:rows.map(p=><tr key={p.id} className="border-b last:border-0"><td className="p-4 font-medium">{p.name}</td><td>{p.sku}</td><td>{money(p.price)}</td><td>{p.stock}</td><td className="flex gap-1 p-2"><Button variant="ghost" size="sm" onClick={()=>open(p)}>Изменить</Button><Button variant="ghost" size="icon" disabled={remove.isPending} onClick={()=>remove.mutate(p.id)} aria-label="Скрыть товар"><Trash2 className="size-4 text-destructive"/></Button></td></tr>)}</tbody></table></div>{editorOpen&&<Editor editing={editing} draft={draft} setDraft={setDraft} categories={categories.data??[]} pending={save.isPending} close={close} save={()=>save.mutate()}/>}</div>
}
function Editor({editing,draft,setDraft,categories,pending,close,save}:{editing:Product|null;draft:Draft;setDraft:(draft:Draft)=>void;categories:{id:number;name:string}[];pending:boolean;close:()=>void;save:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4"><form onSubmit={e=>{e.preventDefault();save()}} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[2rem] bg-card p-7 text-foreground shadow-lift"><div className="flex items-center justify-between"><h2 className="font-display text-3xl font-bold">{editing?'Изменить товар':'Новый товар'}</h2><Button type="button" variant="ghost" size="icon" onClick={close}><X/></Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Название" value={draft.name} onChange={name=>setDraft({...draft,name})}/><Field label="SKU" value={draft.sku} disabled={Boolean(editing)} onChange={sku=>setDraft({...draft,sku})}/><Field label="Бренд" value={draft.brand} onChange={brand=>setDraft({...draft,brand})}/><label className="text-sm">Категория<select value={draft.category_id??''} onChange={e=>setDraft({...draft,category_id:e.target.value?Number(e.target.value):null})} className="mt-1 w-full rounded-xl border bg-background px-3 py-3"><option value="">Без категории</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Цена" type="number" value={String(draft.price)} onChange={price=>setDraft({...draft,price:Number(price)})}/><Field label="Остаток" type="number" value={String(draft.stock)} onChange={stock=>setDraft({...draft,stock:Number(stock)})}/></div><label className="mt-4 block text-sm">Описание<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="mt-1 min-h-28 w-full rounded-xl border bg-background px-3 py-3"/></label><Button className="mt-6 w-full" disabled={pending}>{pending?'Сохраняем...':'Сохранить на backend'}</Button></form></div>}
function Field({label,value,onChange,type='text',disabled=false}:{label:string;value:string;onChange:(value:string)=>void;type?:string;disabled?:boolean}){return <label className="text-sm">{label}<input required disabled={disabled} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border bg-background px-3 py-3 disabled:opacity-60"/></label>}
