import { useDeferredValue, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search, SlidersHorizontal } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { ProductCard } from '../components/ProductCard';
import { useCommerce } from '../features/commerce/useCommerce';
import { rankProducts } from '../lib/utils';
import { api, schemas, type Product } from '../services/api';
type Sort='name'|'price_asc'|'price_desc';
export function CatalogPage(){
 const[query,setQuery]=useState('');const[category,setCategory]=useState<number|null>(null);const[sort,setSort]=useState<Sort>('name');const deferred=useDeferredValue(query);const nav=useNavigate();const commerce=useCommerce();
 const categories=useQuery({queryKey:['catalog','categories'],queryFn:({signal})=>api.get('/catalog/categories',schemas.category.array(),signal)});
 const ranked=rankProducts((commerce.products.data||[]).filter(p=>!category||p.category_id===category).map(p=>({...p,category:categories.data?.find(c=>c.id===p.category_id)?.name})),deferred);
 const rows=deferred?ranked:ranked.sort((a,b)=>sort==='price_asc'?a.price-b.price:sort==='price_desc'?b.price-a.price:a.name.localeCompare(b.name,'ru'));
 const act=async(kind:'cart'|'wishlist',p:Product)=>{if(!commerce.user){nav('/login',{state:{from:'/catalog'}});return}if(kind==='cart')await commerce.addCart.mutateAsync(p.id);else await commerce.toggleWishlist.mutateAsync(p.id)};
 const error=commerce.addCart.error||commerce.toggleWishlist.error;
 return <div className="container py-12 sm:py-16"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-primary">Коллекция</p><h1 className="mt-2 font-display text-5xl font-bold">Каталог мебели</h1><p className="mt-3 text-muted-foreground">{rows.length} предметов для продуманного интерьера</p></div><div className="flex flex-wrap gap-3"><label className="flex min-w-[280px] flex-1 items-center gap-3 rounded-2xl border bg-card px-4 py-3"><Search className="size-5 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по каталогу" className="w-full bg-transparent outline-none"/></label><label className="flex items-center gap-2 rounded-2xl border bg-card px-4"><SlidersHorizontal className="size-4"/><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="bg-transparent py-3"><option value="name">По названию</option><option value="price_asc">Сначала дешевле</option><option value="price_desc">Сначала дороже</option></select></label></div></div><div className="mt-10 flex gap-3 overflow-x-auto pb-2"><button onClick={()=>setCategory(null)} className={`whitespace-nowrap rounded-full px-5 py-2 text-sm ${category===null?'bg-foreground text-background':'border bg-card'}`}>Все</button>{categories.data?.map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={`whitespace-nowrap rounded-full px-5 py-2 text-sm ${category===c.id?'bg-foreground text-background':'border bg-card'}`}>{c.name}</button>)}</div>{error&&<p role="alert" className="mt-6 rounded-xl bg-destructive/10 p-4 text-sm text-destructive">{error.message}</p>}{commerce.products.isLoading?<p className="py-24 text-center">Загружаем каталог...</p>:commerce.products.isError?<p className="my-12 rounded-2xl border border-destructive/30 bg-destructive/5 p-6">{commerce.products.error.message}</p>:rows.length?<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{rows.map(p=><ProductCard key={p.id} product={p} favorite={commerce.wishlist.data?.some(x=>x.product_id===p.id)} pending={commerce.addCart.isPending||commerce.toggleWishlist.isPending} onCart={x=>void act('cart',x)} onFavorite={x=>void act('wishlist',x)}/>)}</div>:<p className="py-24 text-center text-muted-foreground">По вашему запросу ничего не найдено.</p>}</div>
}
