import { Heart, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ProductCard } from '../components/ProductCard';
import { Button } from '../components/ui/button';
import { useCommerce } from '../features/commerce/useCommerce';
import { money } from '../lib/utils';
export function CollectionPage({type}:{type:'favorites'|'cart'}){
 const commerce=useCommerce();const Icon=type==='cart'?ShoppingBag:Heart;const query=type==='cart'?commerce.cart:commerce.wishlist;const error=query.error||commerce.removeCart.error||commerce.updateCart.error||commerce.toggleWishlist.error;
 if(!commerce.user)return <div className="container min-h-[60vh] py-14"><Icon className="size-9 text-primary"/><h1 className="mt-4 font-display text-5xl font-bold">{type==='cart'?'Корзина':'Избранное'}</h1><div className="mt-10 rounded-2xl border bg-card p-8"><p>Войдите, чтобы загрузить данные вашего аккаунта.</p><Button asChild className="mt-5"><Link to="/login" state={{from:type==='cart'?'/cart':'/favorites'}}>Войти</Link></Button></div></div>;
 return <div className="container min-h-[60vh] py-14"><Icon className="size-9 text-primary"/><h1 className="mt-4 font-display text-5xl font-bold">{type==='cart'?'Корзина':'Избранное'}</h1>{error&&<p role="alert" className="mt-6 rounded-xl bg-destructive/10 p-4 text-destructive">{error.message}</p>}{query.isLoading||commerce.products.isLoading?<p className="py-16">Загружаем данные...</p>:type==='favorites'?<Favorites commerce={commerce}/>:<Cart commerce={commerce}/>}</div>
}
function Favorites({commerce}:{commerce:ReturnType<typeof useCommerce>}){return commerce.favoriteProducts.length?<div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{commerce.favoriteProducts.map(p=><ProductCard key={p.id} product={p} favorite pending={commerce.toggleWishlist.isPending} onFavorite={()=>commerce.toggleWishlist.mutate(p.id)} onCart={()=>commerce.addCart.mutate(p.id)}/>)}</div>:<Empty/>}
function Cart({commerce}:{commerce:ReturnType<typeof useCommerce>}){return commerce.cartRows.length?<div className="mt-10 grid gap-8 lg:grid-cols-[1fr_340px]"><div className="grid gap-4">{commerce.cartRows.map(({item,product})=><article key={item.id} className="flex flex-col gap-4 rounded-2xl border bg-card p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-widest text-muted-foreground">{product.brand}</p><Link to={`/catalog/${product.id}`} className="font-display text-xl font-bold">{product.name}</Link><p className="mt-1 font-bold">{money(product.price)}</p></div><div className="flex items-center gap-2"><Button size="icon" variant="outline" disabled={item.quantity<=1||commerce.updateCart.isPending} onClick={()=>commerce.updateCart.mutate({itemId:item.id,quantity:item.quantity-1})}><Minus className="size-4"/></Button><b className="w-8 text-center">{item.quantity}</b><Button size="icon" variant="outline" disabled={commerce.updateCart.isPending} onClick={()=>commerce.updateCart.mutate({itemId:item.id,quantity:item.quantity+1})}><Plus className="size-4"/></Button><Button size="icon" variant="ghost" disabled={commerce.removeCart.isPending} onClick={()=>commerce.removeCart.mutate(item.id)} aria-label="Удалить"><Trash2 className="size-4 text-destructive"/></Button></div></article>)}</div><aside className="h-fit rounded-2xl border bg-card p-6"><h2 className="font-display text-2xl font-bold">Итого</h2><div className="mt-5 flex justify-between"><span>Товаров</span><b>{commerce.cartCount}</b></div><div className="mt-4 flex justify-between border-t pt-4 text-xl"><span>Сумма</span><b>{money(commerce.subtotal)}</b></div><Button asChild className="mt-6 w-full"><Link to="/planner">Создать проект для заказа</Link></Button></aside></div>:<Empty/>}
function Empty(){return <div className="mt-10 rounded-2xl border border-dashed p-12 text-center text-muted-foreground">Здесь пока пусто. <Link className="font-bold text-primary" to="/catalog">Перейти в каталог</Link></div>}
